

ALTER  TABLE USER RENAME TO U_USER;


CREATE TABLE IF NOT EXISTS M_MESSAGE
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	
	MESSAGE 	TEXT,
	USER_ID	INTEGER	,

	CREATED_BY  INTEGER,
	CREATED_TIME DATE,
	UPDATED_BY INTEGER,
	UPDATED_TIME DATE,
	
	PRIMARY KEY(ID)
) DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;


ALTER TABLE M_MESSAGE ADD CONSTRAINT `FK_M_MESSAGE` FOREIGN KEY (USER_ID) REFERENCES U_USER (ID) ON DELETE CASCADE ON UPDATE CASCADE;


 








