
CREATE TABLE IF NOT EXISTS USER
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FIRST_NAME 	VARCHAR(32),	
	LAST_NAME 	VARCHAR(32),
	EMAIL 	VARCHAR(32),
	USER_NAME 	VARCHAR(32),
	PASSWORD 	VARCHAR(32),
	CREATED_BY  INTEGER,
	CREATED_TIME DATE,
	UPDATED_BY INTEGER,
	UPDATED_TIME DATE,
	
	PRIMARY KEY(ID)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


