

ALTER  TABLE M_MESSAGE RENAME TO D_MESSAGE;


CREATE TABLE IF NOT EXISTS G_GROUP
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	
	NAME VARCHAR(32),

	CREATED_BY  INTEGER,
	CREATED_TIME DATE,
	UPDATED_BY INTEGER,
	UPDATED_TIME DATE,
	
	PRIMARY KEY(ID)
) DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS G_GROUP_USER
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	
	USER_ID	INTEGER	,
	GROUP_ID INTEGER,
	
	PRIMARY KEY(ID)
) DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

ALTER TABLE G_GROUP_USER ADD CONSTRAINT `FK_G_GROUP_USER_GROUP_ID` FOREIGN KEY (GROUP_ID) REFERENCES G_GROUP (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE G_GROUP_USER ADD CONSTRAINT `FK_G_GROUP_USER_USER_ID` FOREIGN KEY (USER_ID) REFERENCES U_USER (ID) ON DELETE CASCADE ON UPDATE CASCADE;


CREATE TABLE IF NOT EXISTS G_GROUP_USER_MESSAGE
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	
	GROUP_USER_ID	INTEGER	,
	MESSAGE_ID INTEGER,
	
	PRIMARY KEY(ID)
) DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

ALTER TABLE G_GROUP_USER_MESSAGE ADD CONSTRAINT `FK_GROUP_USER_ID` FOREIGN KEY (GROUP_USER_ID) REFERENCES G_GROUP_USER (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE G_GROUP_USER_MESSAGE ADD CONSTRAINT `FK_MESSAGE_ID` FOREIGN KEY (MESSAGE_ID) REFERENCES D_MESSAGE (ID) ON DELETE CASCADE ON UPDATE CASCADE;









